# develop stage
FROM node:22 as develop-stage
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
# build stage
FROM develop-stage as build-stage
WORKDIR /app
ARG MAT2_API_URL_PROD
ENV MAT2_API_URL_PROD=$MAT2_API_URL_PROD
RUN yarn

EXPOSE 80
